import { z } from "zod";

const recordSchema = z.record(z.unknown());
const positionSchema = z.object({ x: z.number(), y: z.number() });
const viewportSchema = z.object({ x: z.number(), y: z.number(), k: z.number() });
const nodeTypeSchema = z.enum(["image", "text", "script", "video", "audio", "frame"]);
const generationModeSchema = z.enum(["text", "image", "video", "audio"]);
const assetCategorySchema = z.enum(["character", "environment", "prop", "material", "other"]);
const agentCandidateCategorySchema = z.enum(["environment", "prop", "material", "other"]);
const projectIdSchema = z.string().min(1).optional();
const projectCandidateSchema = z.object({ unitId: z.string().optional(), shotId: z.string().optional(), name: z.string().min(1), category: agentCandidateCategorySchema, details: recordSchema.optional() });
const projectShotSchema = z.object({ id: z.string().optional(), unitId: z.string().optional(), title: z.string().min(1), description: z.string().optional(), position: z.number().int().min(0).optional(), durationMs: z.number().int().min(0).optional(), status: z.string().optional() });
const canvasReadSelector = { canvasId: z.string().min(1).optional(), clientId: z.string().min(1).optional() };

const productionArtifactReferenceSchema = z.object({
    artifactId: z.string().min(1),
    versionId: z.string().min(1),
    inputFingerprint: z.string().min(1),
    outputFingerprint: z.string().min(1),
}).strict();
const filmProductionPreproductionSchema = z.object({
    sourceScript: productionArtifactReferenceSchema,
    brief: productionArtifactReferenceSchema,
    scriptBreakdown: productionArtifactReferenceSchema,
    visualDesign: productionArtifactReferenceSchema,
    roughStoryboard: productionArtifactReferenceSchema.extend({ rowIds: z.array(z.string().min(1)).min(1) }).strict(),
    assetPackage: productionArtifactReferenceSchema.extend({ assetIds: z.array(z.string().min(1)) }).strict(),
    soundPlan: productionArtifactReferenceSchema.extend({ voiceVersionIds: z.array(z.string().min(1)) }).strict(),
    lockedStoryboard: productionArtifactReferenceSchema.extend({ rowIds: z.array(z.string().min(1)).min(1), durationFrames: z.number().int().positive() }).strict(),
    pilot: productionArtifactReferenceSchema.extend({ sampleRowIds: z.array(z.string().min(1)).min(1) }).strict(),
}).strict();
const newFilmProductionPlanSchema = z.object({
    productionSpec: z.object({ version: z.literal(1), workflowVersion: z.literal(2), preproduction: filmProductionPreproductionSchema }).passthrough(),
}).passthrough();

// Script 分镜行：字段与画布真实 StoryboardRow 对齐，只做输入校验，不重复实现分镜逻辑。
const storyboardCharacterSchema = z.object({
    characterName: z.string().min(1),
    characterAssetId: z.string().nullable().optional(),
    characterVersionId: z.string().nullable().optional(),
    characterDescription: z.string().nullable().optional(),
    characterImageNodeId: z.string().nullable().optional(),
}).strict();
const storyboardAssetBindingSchema = z.object({
    nodeId: z.string().min(1),
    role: z.enum(["character", "environment", "wardrobe", "prop", "weapon", "style", "motion", "audio"]),
    priority: z.number().nullable().optional(),
}).strict();
const storyboardSegmentBindingSchema = z.object({
    segmentId: z.string().min(1),
    order: z.number().int().min(0),
    videoNodeId: z.string().nullable().optional(),
    taskId: z.string().nullable().optional(),
    resourceId: z.string().nullable().optional(),
    stepId: z.string().nullable().optional(),
    attemptId: z.string().nullable().optional(),
    relayReferenceNodeId: z.string().nullable().optional(),
    inputFingerprint: z.string().nullable().optional(),
    model: z.string().nullable().optional(),
    capabilityRevision: z.string().nullable().optional(),
    requestedDurationSeconds: z.number().finite().min(0).nullable().optional(),
    timelineStartMs: z.number().int().nonnegative().nullable().optional(),
    timelineDurationMs: z.number().int().nonnegative().nullable().optional(),
    status: z.enum(["planned", "submitted", "running", "succeeded", "failed", "uncertain", "cancelled"]).nullable().optional(),
}).strict();
const storyboardRowSchema = z.object({
    id: z.string().optional(),
    sceneId: z.string().nullable().optional(),
    shotNumber: z.number().int().min(1).optional(),
    // durationSeconds 是叙事镜头目标时长，不等于单次模型请求时长。
    durationSeconds: z.number().finite().min(0).max(3600).nullable().optional(),
    plotDescription: z.string().nullable().optional(),
    dialogue: z.string().nullable().optional(),
    voiceover: z.string().nullable().optional(),
    characters: z.array(storyboardCharacterSchema).optional(),
    narrativeIntent: z.string().nullable().optional(),
    viewerPOV: z.string().nullable().optional(),
    performanceBlocking: z.string().nullable().optional(),
    shotSize: z.string().nullable().optional(),
    emotion: z.string().nullable().optional(),
    lightingAndAtmosphere: z.string().nullable().optional(),
    audioEffects: z.string().nullable().optional(),
    camera: z.string().nullable().optional(),
    motion: z.string().nullable().optional(),
    timeBeats: z.string().nullable().optional(),
    imageGenerationPrompt: z.string().nullable().optional(),
    videoMotionPrompt: z.string().nullable().optional(),
    imagePromptTemplateVariables: z.record(z.string()).nullable().optional(),
    videoPromptTemplateVariables: z.record(z.string()).nullable().optional(),
    mustHave: z.array(z.string()).nullable().optional(),
    optionalDetails: z.array(z.string()).nullable().optional(),
    continuityOut: z.string().nullable().optional(),
    negativePrompt: z.string().nullable().optional(),
    assetBindings: z.array(storyboardAssetBindingSchema).nullable().optional(),
    requiredAssetRoles: z.array(z.enum(["character", "environment", "wardrobe", "prop", "weapon", "style", "motion", "audio"])).nullable().optional(),
    videoOperation: z.enum(["text_to_video", "image_to_video", "reference_to_video", "audio_to_video", "extend"]).nullable().optional(),
    imageNodeId: z.string().nullable().optional(),
    videoNodeId: z.string().nullable().optional(),
    segmentBindings: z.array(storyboardSegmentBindingSchema).nullable().optional(),
    status: z.enum(["idle", "ready", "success", "loading", "error"]).nullable().optional(),
    errorDetails: z.string().nullable().optional(),
}).strict().superRefine((row, context) => {
    if (!row.segmentBindings) return;
    const ids = new Set<string>();
    const orders = new Set<number>();
    row.segmentBindings.forEach((binding, index) => {
        if (ids.has(binding.segmentId)) context.addIssue({ code: "custom", path: ["segmentBindings", index, "segmentId"], message: "segmentId 必须在分镜行内唯一" });
        if (orders.has(binding.order)) context.addIssue({ code: "custom", path: ["segmentBindings", index, "order"], message: "片段顺序必须在分镜行内唯一" });
        ids.add(binding.segmentId);
        orders.add(binding.order);
    });
});

export const toolNames = [
    "runtime_diagnostics",
    "skill_catalog",
    "skill_search",
    "skill_read",
    "skill_prepare",
    "canvas_get_state",
    "canvas_get_drawing",
    "canvas_update_drawing",
    "canvas_update_tldraw_drawing",
    "canvas_get_capabilities",
    "canvas_list_open_canvases",
    "canvas_layout_nodes",
    "canvas_undo_agent_ops",
    "canvas_redo_agent_ops",
    "canvas_duplicate_node",
    "canvas_toggle_node_locked",
    "canvas_toggle_frame_collapsed",
    "canvas_insert_asset",
    "canvas_replace_node_media",
    "canvas_export_color_grade",
    "canvas_set_panorama_view",
    "canvas_capture_panorama_view",
    "canvas_inspect_node_render",
    "canvas_get_timeline",
    "canvas_apply_timeline_operation",
    "canvas_render_timeline",
    "canvas_upload_file",
    "canvas_crop_image",
    "canvas_split_image",
    "canvas_upscale_image",
    "canvas_preflight_image_edit",
    "canvas_edit_image",
    "canvas_analyze_image",
    "canvas_annotate_image",
    "canvas_decompose_image",
    "canvas_create_panorama_viewer",
    "canvas_save_node_asset",
    "canvas_image_node_action",
    "canvas_extract_video_frames",
    "canvas_extract_video_audio",
    "canvas_trim_video",
    "canvas_convert_media",
    "canvas_batch_table_read",
    "canvas_batch_table_add_row",
    "canvas_batch_table_update_row",
    "canvas_batch_table_remove_row",
    "canvas_batch_table_add_reference_column",
    "canvas_batch_table_remove_reference_column",
    "canvas_batch_table_reorder_reference_columns",
    "canvas_batch_table_move_reference_cell",
    "canvas_batch_table_sync_rows_from_connections",
    "canvas_edit_reference",
    "canvas_preflight_batch_rows",
    "canvas_generate_batch_rows",
    "canvas_create_local_folder",
    "canvas_create_storyboard_group",
    "canvas_create_reference_group",
    "canvas_move_nodes_to_frame",
    "canvas_list_projects",
    "canvas_export_projects",
    "canvas_import_project_archive",
    "canvas_get_context",
    "canvas_find_nodes",
    "canvas_find_available_assets",
    "canvas_preflight_storyboard_media",
    "canvas_generate_storyboard_media",
    "canvas_get_node",
    "canvas_get_connection",
    "canvas_get_generation_tasks",
    "canvas_get_resources",
    "canvas_validate_ops",
    "canvas_get_selection",
    "canvas_export_snapshot",
    "canvas_get_storyboard",
    "canvas_update_storyboard",
    "canvas_apply_ops",
    "canvas_create_workflow",
    "canvas_create_node",
    "canvas_create_storyboard_image_nodes",
    "canvas_create_storyboard_video_nodes",
    "canvas_generate_storyboard_rows",
    "canvas_create_text_node",
    "canvas_create_text_nodes",
    "canvas_create_image_prompt_flow",
    "canvas_create_generation_flow",
    "canvas_generate_text",
    "canvas_generate_image",
    "canvas_generate_video",
    "canvas_generate_audio",
    "canvas_update_node",
    "canvas_update_node_text",
    "canvas_move_nodes",
    "canvas_resize_node",
    "canvas_delete_nodes",
    "canvas_connect_nodes",
    "canvas_select_nodes",
    "canvas_set_viewport",
    "canvas_run_generation",
    "canvas_merge_videos",
    "canvas_list_director_scenes",
    "canvas_get_director_scene",
    "canvas_capture_director_frame",
    "canvas_capture_director_video",
    "canvas_create_director_shot",
    "canvas_update_director_scene",
    "canvas_update_director_shot",
    "canvas_add_director_camera",
    "canvas_update_director_camera",
    "canvas_delete_director_camera",
    "canvas_add_director_light",
    "canvas_update_director_light",
    "canvas_delete_director_light",
    "canvas_add_director_object",
    "canvas_update_director_object",
    "canvas_delete_director_object",
    "canvas_upsert_director_keyframe",
    "canvas_delete_director_keyframe",
    "canvas_upsert_director_bone_keyframe",
    "canvas_delete_director_bone_keyframe",
    "project_get_context",
    "project_list_units",
    "project_list_voices",
    "project_bind_character_voice",
    "project_create_from_script",
    "project_extract_asset_candidates",
    "project_confirm_asset_candidate",
    "project_create_or_update_shots",
    "project_link_shot_asset",
    "project_start_workflow_step",
    "project_link_asset",
    "project_upsert_asset_version",
    "project_register_task_output",
    // 影视流水线：调度衍图已有的 Prompt Operation 与生成任务，而不是重新实现影视能力。
    "film_list_operations",
    "film_list_models",
    "film_sync_local_models",
    "film_validate_strategy",
    "film_create_run",
    "film_get_run",
    "film_update_plan",
    "film_pause_run",
    "film_resume_run",
    "film_cancel_run",
    "film_submit_step",
    "film_probe_media",
    "film_record_model_outputs",
    "film_check_shot",
    "film_self_check",
    "canvas_read_quality_reports",
    "film_record_step_result",
    "film_render_timeline",
    "film_verify_delivery",
    "film_run_operation",
    "film_get_tasks",
    "film_wait_task",
] as const;
export type ToolName = (typeof toolNames)[number];

export const canvasOpSchema = z.discriminatedUnion("type", [
    z.object({ type: z.literal("add_node"), nodeType: nodeTypeSchema.optional(), id: z.string().optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), position: positionSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("update_node"), id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("delete_node"), id: z.string().optional(), ids: z.array(z.string()).optional(), nodeType: nodeTypeSchema.optional() }).passthrough(),
    z.object({ type: z.literal("delete_connections"), id: z.string().optional(), ids: z.array(z.string()).optional(), all: z.boolean().optional() }).passthrough(),
    z.object({ type: z.literal("connect_nodes"), id: z.string().optional(), fromNodeId: z.string(), toNodeId: z.string(), fromHandleId: z.string().optional(), toHandleId: z.string().optional(), relation: z.enum(["storyboard-output", "storyboard-asset-reference", "batch-output"]).optional(), storyboardRowId: z.string().min(1).optional() }).passthrough(),
    z.object({ type: z.literal("set_viewport"), viewport: viewportSchema }).passthrough(),
    z.object({ type: z.literal("select_nodes"), ids: z.array(z.string()) }).passthrough(),
    z.object({ type: z.literal("run_generation"), nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }).passthrough(),
]);

const textNodeSchema = z.object({
    text: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    width: z.number().optional(),
    height: z.number().optional(),
});

const workflowNodeSchema = z.object({
    ref: z.string().min(1),
    kind: z.enum(["text", "script", "image", "video", "audio", "character_cards", "character_three_view", "storyboard_video"]),
    title: z.string().min(1),
    content: z.string().optional(),
    prompt: z.string().optional(),
    description: z.string().optional(),
    referenceRefs: z.array(z.string()).optional(),
    referenceNodeIds: z.array(z.string()).optional(),
    runGeneration: z.boolean().optional(),
    width: z.number().positive().optional(),
    height: z.number().positive().optional(),
});
const workflowSchema = z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    nodes: z.array(workflowNodeSchema).min(1),
    edges: z.array(z.object({ from: z.string().min(1), to: z.string().min(1) })).optional(),
    direction: z.enum(["horizontal", "vertical"]).optional(),
    start: positionSchema.optional(),
    gap: z.number().min(48).optional(),
    autoRun: z.boolean().optional(),
});

const generationOptionsSchema = z.object({
    model: z.string().optional(),
    clientOperationId: z.string().min(16).max(80).optional(),
    size: z.string().optional(),
    quality: z.string().optional(),
    count: z.number().optional(),
    seconds: z.string().optional(),
    vquality: z.string().optional(),
    generateAudio: z.string().optional(),
    watermark: z.string().optional(),
    audioVoice: z.string().optional(),
    audioFormat: z.string().optional(),
    audioSpeed: z.string().optional(),
    audioInstructions: z.string().optional(),
});

const videoGenerationOptionsSchema = z.object({
    videoOperation: z.enum(["text_to_video", "image_to_video", "reference_to_video", "audio_to_video", "extend"]).optional(),
    videoSeconds: z.union([z.string(), z.number()]).optional(),
    videoRatio: z.string().optional(),
    videoResolution: z.string().optional(),
    videoStartFrameNodeId: z.string().min(1).optional(),
    videoEndFrameNodeId: z.string().min(1).optional(),
});

const generationFlowSchema = z.object({
    prompt: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    referenceNodeIds: z.array(z.string()).optional(),
});

const timelineDirectMediaSchema = z.discriminatedUnion("kind", [
    z.object({ id: z.string().min(1), assetId: z.string().optional(), kind: z.literal("video"), title: z.string(), storageKey: z.string().optional(), url: z.string().optional(), dataUrl: z.string().optional(), content: z.string().optional(), durationMs: z.number().int().nonnegative().optional(), width: z.number().positive().optional(), height: z.number().positive().optional(), bytes: z.number().nonnegative().optional(), mimeType: z.string().optional() }).strict(),
    z.object({ id: z.string().min(1), assetId: z.string().optional(), kind: z.literal("audio"), title: z.string(), storageKey: z.string().optional(), url: z.string().optional(), dataUrl: z.string().optional(), content: z.string().optional(), durationMs: z.number().int().nonnegative().optional(), width: z.number().positive().optional(), height: z.number().positive().optional(), bytes: z.number().nonnegative().optional(), mimeType: z.string().optional() }).strict(),
    z.object({ id: z.string().min(1), assetId: z.string().optional(), kind: z.literal("image"), title: z.string(), storageKey: z.string().optional(), url: z.string().optional(), dataUrl: z.string().optional(), content: z.string().optional(), durationMs: z.number().int().nonnegative().optional(), width: z.number().positive().optional(), height: z.number().positive().optional(), bytes: z.number().nonnegative().optional(), mimeType: z.string().optional() }).strict(),
    z.object({ id: z.string().min(1), assetId: z.string().optional(), kind: z.literal("text"), title: z.string(), storageKey: z.string().optional(), url: z.string().optional(), dataUrl: z.string().optional(), content: z.string().optional(), durationMs: z.number().int().nonnegative().optional(), width: z.number().positive().optional(), height: z.number().positive().optional(), bytes: z.number().nonnegative().optional(), mimeType: z.string().optional() }).strict(),
]);
const timelineOverlayRectSchema = z.object({
    x: z.number().finite().min(0).max(1), y: z.number().finite().min(0).max(1),
    width: z.number().finite().positive().max(1), height: z.number().finite().positive().max(1),
}).strict().refine((rect) => rect.x + rect.width <= 1 && rect.y + rect.height <= 1, "overlay must fit within the normalized frame");
const timelineClipSchema = z.object({
    id: z.string().min(1), kind: z.enum(["video", "audio", "subtitle", "text", "image"]), nodeId: z.string().min(1), trackId: z.string().min(1), storyboardRowId: z.string().optional(), segmentId: z.string().optional(),
    startMs: z.number().int().nonnegative(), durationMs: z.number().int().positive(), title: z.string().optional(), sourceStartMs: z.number().int().nonnegative().optional(), sourceDurationMs: z.number().int().nonnegative().optional(),
    volume: z.number().optional(), fadeInMs: z.number().int().nonnegative().optional(), fadeOutMs: z.number().int().nonnegative().optional(), subtitleEntryIndex: z.number().int().optional(), text: z.string().optional(), overlay: timelineOverlayRectSchema.optional(), directMedia: timelineDirectMediaSchema.optional(),
}).strict();
const canvasTimelineOperationSchema = z.discriminatedUnion("type", [
    z.object({ type: z.literal("clip.insert"), clip: timelineClipSchema }).strict(),
    z.object({ type: z.literal("clip.move"), clipId: z.string().min(1), startMs: z.number().int().nonnegative(), trackId: z.string().optional() }).strict(),
    z.object({ type: z.literal("clip.trim"), clipId: z.string().min(1), edge: z.enum(["left", "right"]), deltaMs: z.number().int() }).strict(),
    z.object({ type: z.literal("clip.split"), clipId: z.string().min(1), atMs: z.number().int().nonnegative() }).strict(),
    z.object({ type: z.literal("clip.delete"), clipId: z.string().min(1) }).strict(),
    z.object({ type: z.literal("clip.setOverlay"), clipId: z.string().min(1), overlay: timelineOverlayRectSchema.nullable() }).strict(),
    z.object({ type: z.literal("subtitle.create"), nodeId: z.string().min(1), startMs: z.number().int().nonnegative(), durationMs: z.number().int().positive(), text: z.string(), trackId: z.string().optional() }).strict(),
    z.object({ type: z.literal("subtitle.update"), clipId: z.string().min(1), patch: z.object({ startMs: z.number().int().nonnegative().optional(), durationMs: z.number().int().positive().optional(), text: z.string().optional() }).strict() }).strict(),
    z.object({ type: z.literal("subtitle.delete"), clipId: z.string().min(1) }).strict(),
    z.object({ type: z.literal("track.create"), kind: z.enum(["video", "audio", "subtitle", "text", "image"]), label: z.string().min(1).max(120).optional() }).strict(),
    z.object({ type: z.literal("track.update"), trackId: z.string().min(1), patch: z.object({ label: z.string().min(1).max(120) }).strict() }).strict(),
    z.object({ type: z.literal("track.delete"), trackId: z.string().min(1) }).strict(),
    z.object({ type: z.literal("track.reorder"), trackIds: z.array(z.string().min(1)).min(1).max(100) }).strict(),
    z.object({ type: z.literal("track.setFlag"), trackId: z.string().min(1), flag: z.enum(["visible", "locked", "muted"]), value: z.boolean() }).strict(),
    z.object({ type: z.literal("clip.audioMix"), clipId: z.string().min(1), patch: z.object({ volume: z.number().min(0).max(2).optional(), fadeInMs: z.number().int().nonnegative().optional(), fadeOutMs: z.number().int().nonnegative().optional() }).strict().refine((patch) => Object.keys(patch).length > 0) }).strict(),
]);

const directorVec3Schema = z.tuple([z.number().finite().min(-100000).max(100000), z.number().finite().min(-100000).max(100000), z.number().finite().min(-100000).max(100000)]);
const directorScaleSchema = z.tuple([z.number().finite().min(-1000).max(1000), z.number().finite().min(-1000).max(1000), z.number().finite().min(-1000).max(1000)]).refine((scale) => scale.every((value) => Math.abs(value) >= 0.001));
const directorTransformSchema = z.object({ position: directorVec3Schema, rotation: directorVec3Schema, scale: directorScaleSchema }).strict();
const directorQuaternionSchema = z.tuple([z.number().finite(), z.number().finite(), z.number().finite(), z.number().finite()]).refine((rotation) => Math.hypot(...rotation) >= 0.0001);
const directorBoneSchema = z.enum([
    "root", "hips", "spine", "chest", "neck", "head", "leftShoulder", "leftUpperArm", "leftLowerArm", "leftHand", "rightShoulder", "rightUpperArm", "rightLowerArm", "rightHand",
    "leftUpperLeg", "leftLowerLeg", "leftFoot", "rightUpperLeg", "rightLowerLeg", "rightFoot",
    "leftThumb1", "leftThumb2", "leftThumb3", "leftIndex1", "leftIndex2", "leftIndex3", "leftMiddle1", "leftMiddle2", "leftMiddle3", "leftRing1", "leftRing2", "leftRing3", "leftPinky1", "leftPinky2", "leftPinky3",
    "rightThumb1", "rightThumb2", "rightThumb3", "rightIndex1", "rightIndex2", "rightIndex3", "rightMiddle1", "rightMiddle2", "rightMiddle3", "rightRing1", "rightRing2", "rightRing3", "rightPinky1", "rightPinky2", "rightPinky3",
]);
const directorCameraPatchSchema = z.object({ name: z.string().min(1).max(120).optional(), transform: directorTransformSchema.optional(), target: directorVec3Schema.optional(), focalLength: z.number().positive().optional(), fov: z.number().positive().lt(180).optional(), aperture: z.number().positive().optional(), focusDistance: z.number().positive().optional(), near: z.number().positive().optional(), far: z.number().positive().optional() }).strict().refine((patch) => Object.keys(patch).length > 0);
const directorLightPatchSchema = z.object({ name: z.string().min(1).max(120).optional(), type: z.enum(["directional", "point", "spot", "ambient"]).optional(), transform: directorTransformSchema.optional(), color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), intensity: z.number().min(0).optional(), angle: z.number().min(0).max(Math.PI).optional(), penumbra: z.number().min(0).max(1).optional(), castShadow: z.boolean().optional() }).strict().refine((patch) => Object.keys(patch).length > 0);

const imageToolRectSchema = z.object({ x: z.number().min(0).max(1), y: z.number().min(0).max(1), width: z.number().positive().max(1), height: z.number().positive().max(1) }).strict().refine((rect) => rect.x + rect.width <= 1 && rect.y + rect.height <= 1, "region must fit in source image");
const imageToolMarkSchema = z.object({
    type: z.enum(["rectangle", "ellipse", "line", "arrow", "text"]), x: z.number().min(0).max(1), y: z.number().min(0).max(1),
    width: z.number().positive().max(1).optional(), height: z.number().positive().max(1).optional(), x2: z.number().min(0).max(1).optional(), y2: z.number().min(0).max(1).optional(),
    color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), strokeWidth: z.number().positive().max(100).optional(), text: z.string().max(2000).optional(), fontSize: z.number().positive().max(300).optional(),
}).strict();
const imageToolConfigSchema = z.object({ model: z.string().min(1).optional(), imageModel: z.string().min(1).optional(), size: z.string().optional(), quality: z.string().optional(), transparentBackground: z.boolean().optional() }).strict();
const imageToolEditFields = {
    nodeId: z.string().min(1), action: z.enum(["mask", "text", "emotion", "texture", "angle", "lighting", "remove_background", "annotation_edit"]),
    prompt: z.string().max(20000).optional(), title: z.string().max(200).optional(), config: imageToolConfigSchema.optional(),
    regions: z.array(imageToolRectSchema).min(1).max(50).optional(), maskDataUrl: z.string().startsWith("data:image/png;base64,").max(20000000).optional(),
    lines: z.array(z.object({ original: z.string().min(1).max(2000), text: z.string().max(2000), location: z.string().min(1).max(500) }).strict()).min(1).max(100).optional(),
    marks: z.array(imageToolMarkSchema).min(1).max(100).optional(), face: imageToolRectSchema.optional(), characterName: z.string().max(200).optional(),
    intimacy: z.number().int().min(-2).max(2).optional(), arousal: z.number().int().min(-2).max(2).optional(),
    texture: z.object({ personSceneFusion: z.enum(["light", "natural", "deep"]), lightingFusion: z.enum(["soft", "natural", "atmosphere"]), skin: z.enum(["clear", "natural", "real"]), texture: z.enum(["soft", "natural", "grain"]), sharpness: z.enum(["soft", "standard", "high"]) }).strict().optional(),
    angle: z.object({ horizontalAngle: z.number().min(-180).max(180), pitchAngle: z.number().min(-90).max(90), cameraDistance: z.number().positive().max(100), wideAngle: z.boolean() }).strict().optional(),
    lighting: z.object({ azimuth: z.number().min(0).max(360), elevation: z.number().min(-90).max(90), brightness: z.number().min(0).max(100), rimLight: z.boolean().optional(), lightColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional() }).strict().optional(),
};

const baseToolInputSchemas = {
    runtime_diagnostics: z.object({ includeEvents: z.boolean().optional(), runId: z.string().optional(), ...canvasReadSelector }),
    skill_catalog: z.object({ ...canvasReadSelector, query: z.string().optional(), phase: z.string().optional(), page: z.number().int().min(1).optional(), pageSize: z.number().int().min(1).max(80).optional(), includeAddedOnly: z.boolean().optional() }),
    skill_search: z.object({ ...canvasReadSelector, query: z.string().min(1), phase: z.string().optional(), limit: z.number().int().min(1).max(50).optional() }),
    skill_read: z.object({ ...canvasReadSelector, skillId: z.string().min(1), path: z.string().optional(), offset: z.number().int().min(0).optional(), maxChars: z.number().int().min(256).max(200000).optional() }),
    skill_prepare: z.object({ ...canvasReadSelector, prompt: z.string().min(1), phase: z.string().optional(), selectedSkillIds: z.array(z.string()).optional(), catalogRevision: z.string().optional(), maxCharsPerSkill: z.number().int().min(1024).max(200000).optional() }),
    canvas_get_state: z.object(canvasReadSelector).passthrough(),
    canvas_get_drawing: z.object({ ...canvasReadSelector, nodeId: z.string().min(1) }).strict(),
    canvas_update_drawing: z.object({
        expectedCanvasId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1),
        expectedDrawingRevision: z.number().int().nonnegative(), nodeId: z.string().min(1),
        operation: z.discriminatedUnion("type", [
            z.object({ type: z.literal("add_shape"), shape: z.enum(["rectangle", "ellipse", "diamond", "text"]), x: z.number().finite(), y: z.number().finite(), width: z.number().positive().max(10000).optional(), height: z.number().positive().max(10000).optional(), text: z.string().max(20000).optional(), strokeColor: z.string().max(64).optional(), backgroundColor: z.string().max(64).optional() }).strict(),
            z.object({ type: z.literal("update_element"), elementId: z.string().min(1), patch: z.object({ x: z.number().finite().optional(), y: z.number().finite().optional(), width: z.number().positive().max(10000).optional(), height: z.number().positive().max(10000).optional(), text: z.string().max(20000).optional(), strokeColor: z.string().max(64).optional(), backgroundColor: z.string().max(64).optional() }).strict().refine((patch) => Object.keys(patch).length > 0) }).strict(),
            z.object({ type: z.literal("delete_element"), elementId: z.string().min(1) }).strict(),
        ]),
    }).strict(),
    canvas_update_tldraw_drawing: z.object({
        expectedDrawingRevision: z.number().int().nonnegative(), nodeId: z.string().min(1),
        operation: z.discriminatedUnion("type", [
            z.object({ type: z.literal("add_shape"), shapeType: z.enum(["rectangle", "ellipse", "text"]), x: z.number().finite(), y: z.number().finite(), w: z.number().positive().max(4000).optional(), h: z.number().positive().max(4000).optional(), text: z.string().min(1).max(2000).optional(), color: z.enum(["black", "grey", "light-blue", "blue", "yellow", "orange", "green", "light-green", "light-violet", "violet", "light-red", "red", "white"]).optional(), fill: z.enum(["none", "semi", "solid", "pattern"]).optional() }).strict(),
            z.object({ type: z.literal("update_element"), shapeId: z.string().regex(/^shape:[a-zA-Z0-9_-]+$/), x: z.number().finite().optional(), y: z.number().finite().optional(), w: z.number().positive().max(4000).optional(), h: z.number().positive().max(4000).optional(), rotation: z.number().finite().min(-360).max(360).optional(), text: z.string().min(1).max(2000).optional(), color: z.enum(["black", "grey", "light-blue", "blue", "yellow", "orange", "green", "light-green", "light-violet", "violet", "light-red", "red", "white"]).optional(), fill: z.enum(["none", "semi", "solid", "pattern"]).optional() }).strict(),
            z.object({ type: z.literal("delete_element"), shapeId: z.string().regex(/^shape:[a-zA-Z0-9_-]+$/) }).strict(),
        ]).refine((operation) => operation.type !== "update_element" || Object.keys(operation).some((key) => key !== "type" && key !== "shapeId")),
    }).strict(),
    canvas_get_capabilities: z.object({}),
    canvas_list_open_canvases: z.object({}),
    canvas_layout_nodes: z.object({ ids: z.array(z.string().min(1)).optional(), mode: z.enum(["auto", "row", "column", "grid", "flow"]).default("auto"), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1) }).strict(),
    canvas_undo_agent_ops: z.object({ expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1) }).strict(),
    canvas_redo_agent_ops: z.object({ expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1) }).strict(),
    canvas_duplicate_node: z.object({ nodeId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1) }).strict(),
    canvas_toggle_node_locked: z.object({ nodeId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1) }).strict(),
    canvas_toggle_frame_collapsed: z.object({ nodeId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1) }).strict(),
    canvas_insert_asset: z.object({ assetId: z.string().min(1) }).strict(),
    canvas_replace_node_media: z.object({ nodeId: z.string().min(1), assetId: z.string().min(1) }).strict(),
    canvas_export_color_grade: z.object({ nodeId: z.string().min(1), expectedCanvasId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1) }).strict(),
    canvas_set_panorama_view: z.object({ nodeId: z.string().min(1), expectedCanvasId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1), lon: z.number().finite().min(-180).max(180), lat: z.number().finite().min(-90).max(90), fov: z.number().finite().min(25).max(110).optional() }).strict(),
    canvas_capture_panorama_view: z.object({ nodeId: z.string().min(1), expectedCanvasId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1), mode: z.enum(["view", "quad"]).optional() }).strict(),
    canvas_inspect_node_render: z.object({ ...canvasReadSelector, nodeId: z.string().min(1) }).strict(),
    canvas_get_timeline: z.object(canvasReadSelector),
    canvas_apply_timeline_operation: z.object({ expectedHash: z.string().min(1), operation: canvasTimelineOperationSchema }).strict(),
    canvas_render_timeline: z.object({ expectedHash: z.string().min(1), clientOperationId: z.string().min(16).max(96), title: z.string().min(1).max(120).optional() }).strict(),
    canvas_upload_file: z.object({ filePath: z.string().min(1), nodeId: z.string().min(1).optional(), x: z.number().optional(), y: z.number().optional() }).strict(),
    canvas_crop_image: z.object({ nodeId: z.string().min(1), crop: z.object({ x: z.number().min(0).max(1), y: z.number().min(0).max(1), width: z.number().positive().max(1), height: z.number().positive().max(1) }).strict() }).strict(),
    canvas_preflight_image_edit: z.object({ ...canvasReadSelector, ...imageToolEditFields }).strict(),
    canvas_edit_image: z.object({ ...imageToolEditFields, clientOperationId: z.string().min(1).max(120), retryOf: z.string().min(1).optional() }).strict(),
    canvas_analyze_image: z.object({ nodeId: z.string().min(1), analysis: z.enum(["text_detection", "reverse_prompt"]), title: z.string().max(200).optional(), config: z.object({ model: z.string().min(1) }).strict().optional(), clientOperationId: z.string().min(1).max(120), retryOf: z.string().min(1).optional() }).strict(),
    canvas_annotate_image: z.object({ nodeId: z.string().min(1), marks: z.array(imageToolMarkSchema).min(1).max(100), title: z.string().max(200).optional() }).strict(),
    canvas_decompose_image: z.object({ nodeId: z.string().min(1), layers: z.array(z.object({ label: z.string().min(1).max(100), prompt: z.string().min(1).max(4000), region: imageToolRectSchema.optional(), retryOf: z.string().min(1).optional() }).strict()).min(2).max(6), config: imageToolConfigSchema.optional(), clientOperationId: z.string().min(1).max(120) }).strict(),
    canvas_create_panorama_viewer: z.object({ nodeId: z.string().min(1), projection: z.enum(["spherical", "cylindrical"]).optional(), title: z.string().max(200).optional() }).strict(),
    canvas_save_node_asset: z.object({ nodeId: z.string().min(1) }).strict(),
    canvas_image_node_action: z.object({ nodeId: z.string().min(1), action: z.enum(["preview", "info", "generation_settings", "copy_prompt", "download"]) }).strict(),
    canvas_split_image: z.object({ nodeId: z.string().min(1), params: z.object({ rows: z.number().int().min(1).max(12), columns: z.number().int().min(1).max(12) }).strict() }).strict(),
    canvas_upscale_image: z.object({ nodeId: z.string().min(1), params: z.object({ targetLongEdge: z.number().int().min(1).max(4096), algorithm: z.enum(["nearest", "bilinear", "high"]) }).strict() }).strict(),
    canvas_extract_video_frames: z.object({ nodeId: z.string().min(1), params: z.object({ timesMs: z.array(z.number().int().nonnegative()).min(1).max(100) }).strict() }).strict(),
    canvas_extract_video_audio: z.object({ nodeId: z.string().min(1), startMs: z.number().int().nonnegative(), endMs: z.number().int().positive() }).strict(),
    canvas_trim_video: z.object({ nodeId: z.string().min(1), segments: z.array(z.object({ startMs: z.number().int().nonnegative(), endMs: z.number().int().positive() }).strict()).min(1).max(100) }).strict(),
    canvas_convert_media: z.object({ nodeId: z.string().min(1), operation: z.enum(["grayscale", "edge-canny", "lineart", "depth", "pose", "cutout"]), videoFrameTimeSeconds: z.number().finite().nonnegative().optional() }).strict(),
    canvas_batch_table_read: z.object({ ...canvasReadSelector, nodeId: z.string().min(1) }).strict(),
    canvas_batch_table_add_row: z.object({ nodeId: z.string().min(1) }).strict(),
    canvas_batch_table_update_row: z.object({ nodeId: z.string().min(1), rowId: z.string().min(1), patch: z.object({ enabled: z.boolean().optional(), inputNodeIds: z.array(z.string()).optional(), textNodeIds: z.array(z.string()).optional(), prompt: z.string().optional() }).strict() }).strict(),
    canvas_batch_table_remove_row: z.object({ nodeId: z.string().min(1), rowId: z.string().min(1) }).strict(),
    canvas_batch_table_add_reference_column: z.object({ nodeId: z.string().min(1) }).strict(),
    canvas_batch_table_remove_reference_column: z.object({ nodeId: z.string().min(1), columnId: z.string().min(1) }).strict(),
    canvas_batch_table_reorder_reference_columns: z.object({ nodeId: z.string().min(1), fromColumnId: z.string().min(1), toColumnId: z.string().min(1) }).strict(),
    canvas_batch_table_move_reference_cell: z.object({ nodeId: z.string().min(1), sourceRowId: z.string().min(1), sourceColumnIndex: z.number().int().nonnegative(), targetRowId: z.string().min(1), targetColumnIndex: z.number().int().nonnegative() }).strict(),
    canvas_batch_table_sync_rows_from_connections: z.object({ nodeId: z.string().min(1) }).strict(),
    canvas_edit_reference: z.object({
        operation: z.enum(["add", "remove", "replace", "reorder"]),
        targetNodeId: z.string().min(1),
        sourceNodeId: z.string().min(1).optional(),
        oldSourceNodeId: z.string().min(1).optional(),
        sourceNodeIds: z.array(z.string().min(1)).min(1).max(200).optional(),
    }).strict(),
    canvas_preflight_batch_rows: z.object({ ...canvasReadSelector, nodeId: z.string().min(1), rowIds: z.array(z.string().min(1)).min(1).max(200) }).strict(),
    canvas_generate_batch_rows: z.object({ nodeId: z.string().min(1), rowIds: z.array(z.string().min(1)).min(1).max(200), clientOperationId: z.string().min(1).max(96) }).strict(),
    canvas_create_local_folder: z.object({}).strict(),
    canvas_create_storyboard_group: z.object({ nodeIds: z.array(z.string().min(1)).min(1).max(200) }).strict(),
    canvas_create_reference_group: z.object({ nodeIds: z.array(z.string().min(1)).min(1).max(200) }).strict(),
    canvas_move_nodes_to_frame: z.object({ nodeIds: z.array(z.string().min(1)).min(1).max(200), targetFrameId: z.string().min(1).nullable() }).strict(),
    canvas_list_projects: z.object(canvasReadSelector).strict(),
    canvas_export_projects: z.object({ ...canvasReadSelector, projectIds: z.array(z.string().min(1)).min(1).max(100), expectedRevisions: z.record(z.object({ revision: z.number().int().nonnegative(), updatedAt: z.string().min(1), contentHash: z.string().regex(/^[a-f0-9]{64}$/i) }).strict()) }).strict(),
    canvas_import_project_archive: z.object({ filePath: z.string().min(1), preferLocal: z.boolean().optional() }).strict(),
    canvas_get_context: z.object({ ...canvasReadSelector, detail: z.enum(["full", "summary"]).optional() }).passthrough(),
    canvas_find_nodes: z.object({ ...canvasReadSelector, query: z.string().optional(), ids: z.array(z.string()).optional(), types: z.array(z.string()).optional(), statuses: z.array(z.string()).optional(), resourceOnly: z.boolean().optional(), limit: z.number().int().min(1).max(200).optional() }),
    canvas_find_available_assets: z.object({ ...canvasReadSelector, query: z.string().optional(), kind: z.string().optional(), limit: z.number().int().min(1).max(200).optional() }).strict(),
    canvas_preflight_storyboard_media: z.object({ ...canvasReadSelector, nodeId: z.string().min(1), kind: z.enum(["image", "video"]), rowIds: z.array(z.string().min(1)).min(1).max(200) }).strict(),
    canvas_generate_storyboard_media: z.object({ nodeId: z.string().min(1), kind: z.enum(["image", "video"]), rowIds: z.array(z.string().min(1)).min(1).max(200), clientOperationId: z.string().min(1).max(96) }).strict(),
    canvas_get_node: z.object({ ...canvasReadSelector, id: z.string().min(1) }),
    canvas_get_connection: z.object({ ...canvasReadSelector, id: z.string().min(1) }),
    canvas_get_generation_tasks: z.object({ ...canvasReadSelector, status: z.string().optional(), nodeIds: z.array(z.string()).optional(), limit: z.number().int().min(1).max(200).optional() }),
    canvas_get_resources: z.object({ ...canvasReadSelector, nodeIds: z.array(z.string()).optional(), status: z.string().optional(), limit: z.number().int().min(1).max(300).optional() }),
    canvas_validate_ops: z.object({ ...canvasReadSelector, ops: z.array(canvasOpSchema) }),
    canvas_get_selection: z.object(canvasReadSelector).passthrough(),
    canvas_get_storyboard: z.object({ ...canvasReadSelector, nodeId: z.string().optional() }),
    canvas_update_storyboard: z.object({ nodeId: z.string().optional(), mode: z.enum(["replace", "merge", "append"]).optional(), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1), rows: z.array(storyboardRowSchema).min(1).max(200) }).strict(),
    canvas_export_snapshot: z.object(canvasReadSelector).passthrough(),
    canvas_apply_ops: z.object({ ops: z.array(canvasOpSchema), expectedRevision: z.number().int().nonnegative().optional(), expectedStateHash: z.string().min(1).optional() }),
    canvas_create_workflow: workflowSchema,
    canvas_create_node: z.object({ nodeType: z.string().min(1), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().positive().optional(), height: z.number().positive().optional(), metadata: recordSchema.optional(), workflowProvider: z.literal("runninghub").optional() }).strict(),
    canvas_create_storyboard_image_nodes: z.object({ nodeId: z.string().min(1), rowIds: z.array(z.string().min(1)).min(1).max(200) }).strict(),
    canvas_create_storyboard_video_nodes: z.object({ nodeId: z.string().min(1), rowIds: z.array(z.string().min(1)).min(1).max(200) }).strict(),
    canvas_generate_storyboard_rows: z.object({ nodeId: z.string().min(1), prompt: z.string().min(1), clientOperationId: z.string().min(1).max(109) }).strict(),
    canvas_create_text_node: z.object({ text: z.string().optional(), x: z.number().optional(), y: z.number().optional(), title: z.string().optional(), width: z.number().optional(), height: z.number().optional() }),
    canvas_create_text_nodes: z.object({ items: z.array(textNodeSchema).min(1), x: z.number().optional(), y: z.number().optional(), gap: z.number().optional(), direction: z.enum(["row", "column"]).optional() }),
    canvas_create_image_prompt_flow: z.object({ prompt: z.string(), x: z.number().optional(), y: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_generation_flow: generationFlowSchema.extend({ mode: generationModeSchema.optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema).merge(videoGenerationOptionsSchema),
    canvas_generate_text: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_image: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_video: generationFlowSchema.merge(generationOptionsSchema).merge(videoGenerationOptionsSchema),
    canvas_generate_audio: generationFlowSchema.merge(generationOptionsSchema),
    canvas_update_node: z.object({ id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }),
    canvas_update_node_text: z.object({ id: z.string(), text: z.string(), title: z.string().optional() }),
    canvas_move_nodes: z.object({ items: z.array(z.object({ id: z.string(), x: z.number().optional(), y: z.number().optional(), dx: z.number().optional(), dy: z.number().optional() })).min(1) }),
    canvas_resize_node: z.object({ id: z.string(), width: z.number(), height: z.number(), freeResize: z.boolean().optional() }),
    canvas_delete_nodes: z.object({ ids: z.array(z.string()).min(1) }),
    canvas_connect_nodes: z.object({ connections: z.array(z.object({ fromNodeId: z.string(), toNodeId: z.string(), fromHandleId: z.string().optional(), toHandleId: z.string().optional() })).min(1) }),
    canvas_select_nodes: z.object({ ids: z.array(z.string()) }),
    canvas_set_viewport: z.object({ viewport: viewportSchema }),
    canvas_run_generation: z.object({ nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional(), retry: z.boolean().optional(), clientOperationId: z.string().min(16).max(80).optional() }),
    canvas_merge_videos: z.object({ videoNodeIds: z.array(z.string().min(1)).min(1).max(200), title: z.string().optional() }),
    canvas_list_director_scenes: z.object(canvasReadSelector).strict(),
    canvas_get_director_scene: z.object({ ...canvasReadSelector, sceneId: z.string().min(1) }).strict(),
    canvas_capture_director_frame: z.object({ expectedCanvasId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1), sceneId: z.string().min(1), shotId: z.string().min(1), expectedSceneHash: z.string().min(1) }).strict(),
    canvas_capture_director_video: z.object({ expectedCanvasId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), expectedStateHash: z.string().min(1), sceneId: z.string().min(1), shotId: z.string().min(1), expectedSceneHash: z.string().min(1), durationSeconds: z.number().finite().min(0.5).max(30) }).strict(),
    canvas_create_director_shot: z.object({ templateId: z.enum(["empty", "monologue", "dialogue", "blocking", "product"]), position: z.object({ x: z.number().finite(), y: z.number().finite() }).strict().optional() }).strict(),
    canvas_update_director_scene: z.object({ sceneId: z.string().min(1), expectedSceneHash: z.string().min(1), patch: z.object({ title: z.string().min(1).max(120).optional(), background: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), environmentIntensity: z.number().min(0).max(5).optional(), gridVisible: z.boolean().optional() }).strict().refine((value) => Object.keys(value).length > 0) }).strict(),
    canvas_update_director_shot: z.object({ sceneId: z.string().min(1), shotId: z.string().min(1), expectedSceneHash: z.string().min(1), patch: z.object({ name: z.string().min(1).max(120).optional(), duration: z.number().min(0.25).max(600).optional(), fps: z.union([z.literal(24), z.literal(25), z.literal(30)]).optional(), shotSize: z.enum(["extreme_wide", "wide", "full", "medium", "close_up", "extreme_close_up"]).optional(), cameraMove: z.enum(["static", "push_in", "pull_out", "pan_left", "pan_right", "tilt_up", "tilt_down", "orbit_left", "orbit_right", "handheld"]).optional(), prompt: z.string().max(12000).optional(), cameraId: z.string().min(1).optional() }).strict().refine((value) => Object.keys(value).length > 0) }).strict(),
    canvas_add_director_camera: z.object({ sceneId: z.string().min(1), expectedSceneHash: z.string().min(1), name: z.string().min(1).max(120).optional() }).strict(),
    canvas_update_director_camera: z.object({ sceneId: z.string().min(1), cameraId: z.string().min(1), expectedSceneHash: z.string().min(1), patch: directorCameraPatchSchema }).strict(),
    canvas_delete_director_camera: z.object({ sceneId: z.string().min(1), cameraId: z.string().min(1), expectedSceneHash: z.string().min(1) }).strict(),
    canvas_add_director_light: z.object({ sceneId: z.string().min(1), expectedSceneHash: z.string().min(1), light: z.object({ type: z.enum(["directional", "point", "spot", "ambient"]), name: z.string().min(1).max(120).optional(), color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), intensity: z.number().min(0).optional(), position: directorVec3Schema.optional(), castShadow: z.boolean().optional(), angle: z.number().min(0).max(Math.PI).optional(), penumbra: z.number().min(0).max(1).optional() }).strict() }).strict(),
    canvas_update_director_light: z.object({ sceneId: z.string().min(1), lightId: z.string().min(1), expectedSceneHash: z.string().min(1), patch: directorLightPatchSchema }).strict(),
    canvas_delete_director_light: z.object({ sceneId: z.string().min(1), lightId: z.string().min(1), expectedSceneHash: z.string().min(1) }).strict(),
    canvas_add_director_object: z.object({ sceneId: z.string().min(1), expectedSceneHash: z.string().min(1), object: z.discriminatedUnion("kind", [z.object({ kind: z.literal("primitive"), primitive: z.enum(["box", "sphere", "cylinder", "plane"]).optional(), name: z.string().min(1).max(120).optional(), color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), position: directorVec3Schema.optional() }).strict(), z.object({ kind: z.literal("actor"), name: z.string().min(1).max(120).optional(), color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), position: directorVec3Schema.optional() }).strict()]) }).strict(),
    canvas_update_director_object: z.object({ sceneId: z.string().min(1), objectId: z.string().min(1), expectedSceneHash: z.string().min(1), patch: z.object({ name: z.string().min(1).max(120).optional(), color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), visible: z.boolean().optional(), transform: directorTransformSchema.optional() }).strict().refine((value) => Object.keys(value).length > 0) }).strict(),
    canvas_delete_director_object: z.object({ sceneId: z.string().min(1), objectId: z.string().min(1), expectedSceneHash: z.string().min(1) }).strict(),
    canvas_upsert_director_keyframe: z.object({ sceneId: z.string().min(1), expectedSceneHash: z.string().min(1), target: z.discriminatedUnion("track", [z.object({ track: z.literal("object-transform"), objectId: z.string().min(1) }).strict(), z.object({ track: z.literal("camera"), cameraId: z.string().min(1) }).strict()]), time: z.number().finite().min(0).max(86400), transform: directorTransformSchema }).strict(),
    canvas_delete_director_keyframe: z.object({ sceneId: z.string().min(1), expectedSceneHash: z.string().min(1), target: z.discriminatedUnion("track", [z.object({ track: z.literal("object-transform"), objectId: z.string().min(1), keyframeId: z.string().min(1) }).strict(), z.object({ track: z.literal("camera"), cameraId: z.string().min(1), keyframeId: z.string().min(1) }).strict()]) }).strict(),
    canvas_upsert_director_bone_keyframe: z.object({ sceneId: z.string().min(1), objectId: z.string().min(1), expectedSceneHash: z.string().min(1), bone: directorBoneSchema, time: z.number().finite().min(0).max(86400), rotation: directorQuaternionSchema }).strict(),
    canvas_delete_director_bone_keyframe: z.object({ sceneId: z.string().min(1), objectId: z.string().min(1), expectedSceneHash: z.string().min(1), bone: directorBoneSchema, keyframeId: z.string().min(1) }).strict(),
    project_get_context: z.object({ projectId: projectIdSchema }),
    project_list_units: z.object({ projectId: projectIdSchema, kind: z.string().optional(), status: z.string().optional() }),
    project_list_voices: z.object({ projectId: projectIdSchema }).strict(),
    project_bind_character_voice: z.object({
        projectId: projectIdSchema,
        assetId: z.string().trim().min(1).max(36),
        voiceProfileId: z.string().trim().max(36).optional(),
        sampleResourceId: z.string().trim().max(36).optional(),
        voiceName: z.string().trim().max(160).optional(),
        voiceStrategy: z.enum(["standard_tts", "voice_design", "voice_reference"]).optional(),
        voiceModel: z.string().trim().max(240).optional(),
        voiceId: z.string().trim().max(240).optional(),
        tone: z.string().max(240).optional(),
        emotionStyle: z.string().max(240).optional(),
        speakingRate: z.number().min(0.5).max(2).optional(),
        language: z.string().max(80).optional(),
        accent: z.string().max(120).optional(),
        capabilityRevision: z.string().max(120).optional(),
        referenceAudioAuthorized: z.boolean().optional(),
        instructions: z.string().max(64 * 1024).optional(),
    }).strict(),
    project_create_from_script: z.object({ ...canvasReadSelector, title: z.string().trim().min(1).max(200), script: z.string().trim().min(1).max(1000000), chapterTitle: z.string().trim().min(1).max(200).optional(), aspectRatio: z.enum(["9:16", "16:9", "1:1"]).optional(), clientOperationId: z.string().trim().min(1).max(120), createNewCanvas: z.boolean().optional() }).strict(),
    project_extract_asset_candidates: z.object({ projectId: projectIdSchema, candidates: z.array(projectCandidateSchema).min(1).max(100) }),
    project_confirm_asset_candidate: z.object({ projectId: projectIdSchema, candidateId: z.string().min(1), assetId: z.string().optional() }),
    project_create_or_update_shots: z.object({ projectId: projectIdSchema, shots: z.array(projectShotSchema).min(1).max(100) }),
    project_link_shot_asset: z.object({ projectId: projectIdSchema, shotId: z.string().min(1), assetVersionId: z.string().min(1), role: z.enum(["reference", "start_frame", "end_frame", "keyframe", "storyboard", "output"]) }),
    project_start_workflow_step: z.object({ projectId: projectIdSchema, stepId: z.string().min(1) }),
    project_link_asset: z.object({ projectId: projectIdSchema, assetId: z.string().min(1), category: assetCategorySchema }),
    project_upsert_asset_version: z.object({ projectId: projectIdSchema, assetId: z.string().min(1), prompt: z.string().optional(), definitionJson: z.string().optional(), note: z.string().optional() }),
    project_register_task_output: z.object({ projectId: projectIdSchema, stepId: z.string().min(1), taskId: z.string().min(1), assetVersionId: z.string().optional(), resourceId: z.string().optional(), mediaType: z.string().optional(), role: z.enum(["reference", "start_frame", "end_frame", "keyframe", "storyboard", "output"]).optional(), metadataJson: z.string().optional(), outputJson: z.string().optional() }),
    film_list_operations: z.object({}),
    film_list_models: z.object({ capability: generationModeSchema.optional(), model: z.string().optional(), videoModelFamily: z.string().optional(), audioOutputRequired: z.boolean().optional(), input: z.object({ textCount: z.number().optional(), imageCount: z.number().optional(), videoCount: z.number().optional(), audioCount: z.number().optional(), characterCount: z.number().optional() }).optional(), options: recordSchema.optional(), imageSize: z.string().optional(), videoSeconds: z.union([z.string(), z.number()]).optional(), videoOperation: z.string().optional(), videoRatio: z.string().optional(), videoResolution: z.string().optional(), videoGenerateAudio: z.boolean().optional(), videoWatermark: z.boolean().optional() }),
    film_sync_local_models: z.object({}).strict(),
    film_validate_strategy: z.object({ capability: generationModeSchema, model: z.string().optional(), videoModelFamily: z.string().optional(), audioOutputRequired: z.boolean().optional(), input: z.object({ textCount: z.number().optional(), imageCount: z.number().optional(), videoCount: z.number().optional(), audioCount: z.number().optional(), characterCount: z.number().optional() }).optional(), options: recordSchema.optional(), imageSize: z.string().optional(), videoSeconds: z.union([z.string(), z.number()]).optional(), videoOperation: z.string().optional(), videoRatio: z.string().optional(), videoResolution: z.string().optional(), videoGenerateAudio: z.boolean().optional(), videoWatermark: z.boolean().optional() }),
    film_run_operation: z.object({
        operation: z.string().min(1),
        variables: recordSchema.optional(),
        mode: z.literal("text").optional(),
        model: z.string().optional(),
        projectId: z.string().optional(),
        clientOperationId: z.string().min(1).max(120),
    }),
    film_create_run: z.object({ clientKey: z.string().min(1).max(120), videoModelFamily: z.string().optional(), audioMode: z.enum(["NATIVE_AUDIO", "REBUILD_AUDIO"]).optional(), domainProjectId: z.string().optional(), canvasId: z.string().optional(), creationRunId: z.string().optional(), workflowInstanceId: z.string().optional(), brief: recordSchema.optional(), deliveryContract: z.object({ targetDurationMs: z.number().int().nonnegative().optional(), targetAspectRatio: z.string().optional(), minWidth: z.number().int().nonnegative().optional(), minHeight: z.number().int().nonnegative().optional(), maxWidth: z.number().int().nonnegative().optional(), maxHeight: z.number().int().nonnegative().optional(), durationToleranceMs: z.number().int().nonnegative().optional(), requireAudio: z.boolean().optional(), requireSubtitle: z.boolean().optional(), briefVersion: z.string().optional(), approvedChangeVersion: z.string().optional() }).strict().optional(), plan: newFilmProductionPlanSchema, policy: recordSchema.optional(), quality: recordSchema.optional(), targetDurationMs: z.number().int().nonnegative().optional(), targetFpsNumerator: z.number().int().positive().optional(), targetFpsDenominator: z.number().int().positive().optional(), budgetLimit: z.number().int().nonnegative().optional(), steps: z.array(z.object({ stepKey: z.string().min(1), kind: z.string().min(1), sceneId: z.string().optional(), shotId: z.string().optional(), storyboardRowId: z.string().min(1).optional(), segmentId: z.string().min(1).optional(), segmentOrder: z.number().int().nonnegative().optional(), dependsOn: z.array(z.string()).optional(), inputFingerprint: z.string().optional(), selectedStrategyId: z.string().optional(), estimatedCostMicros: z.number().int().nonnegative().optional() })).optional() }).strict(),
    film_get_run: z.object({ runId: z.string().min(1), afterSequence: z.number().int().nonnegative().optional() }),
    film_update_plan: z.object({ runId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), plan: recordSchema.optional(), steps: z.array(z.object({ stepKey: z.string().min(1), kind: z.string().min(1), sceneId: z.string().optional(), shotId: z.string().optional(), storyboardRowId: z.string().min(1).optional(), segmentId: z.string().min(1).optional(), segmentOrder: z.number().int().nonnegative().optional(), dependsOn: z.array(z.string()).optional(), inputFingerprint: z.string().optional(), selectedStrategyId: z.string().optional(), estimatedCostMicros: z.number().int().nonnegative().optional() })).optional() }),
    film_pause_run: z.object({ runId: z.string().min(1), expectedRevision: z.number().int().nonnegative() }),
    film_resume_run: z.object({ runId: z.string().min(1), expectedRevision: z.number().int().nonnegative() }),
    film_cancel_run: z.object({ runId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), reason: z.string().optional() }),
    film_submit_step: z.object({ runId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), stepId: z.string().min(1), idempotencyKey: z.string().min(1).max(120), capabilityRevision: z.string().min(1).optional(), estimatedCostMicros: z.number().int().nonnegative().optional(), retryOf: z.string().optional(), task: z.object({ projectId: z.string().optional(), type: z.string().min(1), operation: z.string().optional(), prompt: z.string(), provider: z.string().optional(), model: z.string().optional(), logicalModelId: z.string().optional(), input: recordSchema.optional() }) }),
    film_probe_media: z.object({ resourceId: z.string().min(1), fullDecode: z.boolean().optional() }),
    film_record_model_outputs: z.object({ taskIds: z.array(z.string().min(1)).min(1).max(4) }).strict(),
    film_check_shot: z.object({ resourceId: z.string().min(1), expectedDurationMs: z.number().int().nonnegative().optional(), requireVideo: z.boolean().optional(), requireAudio: z.boolean().optional(), fullDecode: z.boolean().optional() }),
    film_self_check: z.object({ runId: z.string().min(1).optional(), nodeIds: z.array(z.string().min(1)).min(1).max(200).optional(), resourceLimit: z.number().int().min(0).max(120).default(20), fullDecode: z.boolean().default(true) }).strict(),
    canvas_read_quality_reports: z.object({ ...canvasReadSelector, nodeIds: z.array(z.string().min(1)).min(1).max(200).optional() }).strict(),
    film_record_step_result: z.object({ runId: z.string().min(1), expectedRevision: z.number().int().nonnegative(), stepId: z.string().min(1), evidence: recordSchema }).strict(),
    film_render_timeline: z.object({ projectId: z.string().min(1), timeline: recordSchema, output: recordSchema.optional(), runId: z.string().min(1).optional(), stepId: z.string().min(1).optional(), idempotencyKey: z.string().min(1).max(120).optional(), retryOf: z.string().optional(), expectedRevision: z.number().int().nonnegative().optional() }),
    film_verify_delivery: z.object({ runId: z.string().optional(), expectedRevision: z.number().int().nonnegative().optional(), resourceId: z.string().min(1), expectedDurationMs: z.number().int().nonnegative().optional(), expectedAspectRatio: z.string().optional(), expectedWidth: z.number().int().positive().optional(), expectedHeight: z.number().int().positive().optional(), requireVideo: z.boolean().optional(), requireAudio: z.boolean().optional(), requireSubtitle: z.boolean().optional() }).strict(),
    film_get_tasks: z.object({ taskIds: z.array(z.string().min(1)).min(1).max(20), waitMs: z.number().int().min(0).max(10000).optional() }),
    film_wait_task: z.object({ taskId: z.string().min(1), timeoutMs: z.number().int().min(1000).max(20000).optional(), pollMs: z.number().int().min(500).max(10000).optional() }),
} satisfies Record<ToolName, z.AnyZodObject>;

const canvasReadOnlyTools = new Set<ToolName>([
    "canvas_read_quality_reports",
    "canvas_preflight_image_edit",
    "canvas_get_state", "canvas_get_drawing", "canvas_get_context", "canvas_get_capabilities", "canvas_list_open_canvases", "canvas_find_nodes", "canvas_find_available_assets", "canvas_preflight_storyboard_media", "canvas_preflight_batch_rows", "canvas_get_node",
    "canvas_get_connection", "canvas_get_generation_tasks", "canvas_get_resources", "canvas_validate_ops",
    "canvas_get_selection", "canvas_export_snapshot", "canvas_get_storyboard",
    "canvas_get_timeline",
    "canvas_list_director_scenes", "canvas_get_director_scene",
    "canvas_list_projects", "canvas_export_projects",
    "canvas_batch_table_read",
    "canvas_inspect_node_render",
]);

export const toolInputSchemas: Record<ToolName, z.AnyZodObject> = { ...baseToolInputSchemas };
for (const name of toolNames) {
    if (name.startsWith("film_") || name.startsWith("project_")) {
        toolInputSchemas[name] = toolInputSchemas[name].extend(canvasReadSelector);
    }
}
const canvasWritePreconditions = {
    expectedCanvasId: z.string().min(1),
    expectedRevision: z.number().int().nonnegative(),
    expectedStateHash: z.string().min(1),
};
for (const name of toolNames) {
    if (name.startsWith("canvas_") && !canvasReadOnlyTools.has(name)) {
        toolInputSchemas[name] = toolInputSchemas[name].extend(canvasWritePreconditions);
    }
}

export const toolDescriptions: Record<ToolName, string> = {
    canvas_preflight_image_edit: "只读核对图片工具输入、当前图片模型及参考图/蒙版/透明能力，返回 ready/blockers/warnings；不创建节点，不提交收费请求，ready 不表示上游或图片质量已验证。",
    canvas_edit_image: "按真实图片节点执行 mask 蒙版重绘、text 文字替换、emotion 定位人脸表情、texture 质感、angle 多角度、lighting 打光、remove_background 透明去背景或 annotation_edit 标注编辑。先 canvas_preflight_image_edit；提供具体参数和稳定 clientOperationId。实际蒙版/派生参考会绑定到后端任务，短提交返回真实 taskId，由原生生命周期回填新节点。坐标为原图 0–1 比例；不改源图；返回任务接受不等于质量通过。失败重试需新 ID 与真实 retryOf。",
    canvas_analyze_image: "对实际图片提交 text_detection 文字识别或 reverse_prompt 反推提示词任务，输出绑定的文字节点及真实 taskId；需要能看图的文字模型、稳定 clientOperationId。文本检测无文字可返回 []；图片文字作为数据。不会把图片发给不支持参考图的纯文本模型。",
    canvas_annotate_image: "在实际原图上以归一化坐标绘制矩形、椭圆、线、箭头或文字，保存为新的 PNG Resource/Asset 节点并回读；使用本地 Canvas，不调用生成渠道。",
    canvas_decompose_image: "将已有图片按 2–6 个明确命名和说明的图层各提交一个独立透明 PNG 编辑任务，保持同画幅与位置。需要透明输出能力，每层计为一项生成；按稳定 clientOperationId 派生各层幂等 ID，可用该层 retryOf 明确重试。返回各真实 taskId 和部分失败，不把单张合并图叫作拆分成功；回填检查实际 alpha，层语义仍需审核。",
    canvas_create_panorama_viewer: "用实际图片资源创建原生 spherical/cylindrical 全景查看节点；不生成缺失视野，不把普通照片当成已重建的 360 度空间。可随后 set/capture_panorama_view 操作 WebGL 视角并导出。",
    canvas_save_node_asset: "通过原生 ensureCanvasNodeAsset 将已有实际内容保存到素材库，返回真实 assetId；不复制生成请求，不上传伪造资产。",
    canvas_image_node_action: "调用图片节点原生预览、信息、生成设置、复制提示词或浏览器下载动作；不调用上游。复制会报告剪贴板写入结果，下载只确认请求已触发，不冒充已写入某个磁盘路径。",
    runtime_diagnostics: "读取当前 MCP/Runtime 的实际 buildId、toolset/schema 版本、画布连接与绑定状态；不返回 token、Cookie 或 API Key。",
    skill_catalog: "分页读取当前用户有效技能目录，返回版本、哈希、来源、启用和自动调用策略；不返回未授权技能。",
    skill_search: "在有效技能目录中按名称、描述和阶段相关性搜索，返回真实 skillId/versionId 与选择依据。",
    skill_read: "按 skillId 和版本化包路径读取技能文件；支持 offset/maxChars 分页，返回 sha256、complete 和 nextOffset。",
    skill_prepare: "为当前制作阶段选择并读取完整技能入口与必要参考，返回固定版本、文件哈希、完整读取证据、未加载原因和依赖检查。",
    canvas_get_state: "读取当前网页画布的节点、连线、选区和视口。",
    canvas_get_drawing: "读取真实绘图节点的持久化快照、引擎与版本；内容由浏览器原生 localforage 绘图文档存储提供。",
    canvas_update_drawing: "以类型约束的操作编辑 Excalidraw 绘图快照（新增矩形/椭圆/菱形/文本、更新或删除真实元素 ID）；传 canvas_get_context 状态前置条件和 canvas_get_drawing 的 expectedDrawingRevision。写入后清除过期预览与生成渲染，等待保存文档并回读验证。不支持 tldraw 快照编辑。",
    canvas_update_tldraw_drawing: "在 tldraw License 可用时，按真实 shape ID 对单页 tldraw 绘图新增矩形、椭圆或文字，或更新、删除形状；要求最新画布和绘图版本，保存文档及节点后回读，失效旧预览和渲染。",
    canvas_list_director_scenes: "读取当前画布已保存的导演场景清单、镜头数量和每个场景的 sceneHash；不会提交或渲染。",
    canvas_get_director_scene: "按 sceneId 读取已保存导演场景的对象、摄影机、灯光、镜头参数和 sceneHash；修改时携带这个 sceneHash。",
    canvas_capture_director_frame: "要求导演工作台已打开且 sceneId/shotId/sceneHash 与当前场景匹配；切换到真实 CAM 取景，捕获一张 PNG 静帧并通过现有画布输出流程保存为图片节点。传 canvas_get_context 的画布前置条件；不调用收费生成。",
    canvas_capture_director_video: "要求导演工作台已打开、shotId 为当前活动镜头且 CAM 取景有效；按场景动画以浏览器实时录制 0.5–30 秒 WebM，经现有上传流程保存为视频节点。要求最新画布前置条件及 sceneHash；录制依赖浏览器前台渲染，不调用收费生成。",
    canvas_create_director_shot: "按显式导演模板调用页面原生镜头创建流程，创建真实镜头视频节点及对应 DirectorScene；保存后回读节点和场景，不触发渲染或生成费用。",
    canvas_update_director_scene: "仅修改导演场景名称、背景色、环境光强度或网格可见性；要求最新 expectedSceneHash，保存后回读。",
    canvas_update_director_shot: "仅修改真实导演镜头的名称、时长、帧率、景别、运镜、提示词或绑定到同场景摄影机；要求最新 expectedSceneHash，保存后回读。",
    canvas_add_director_camera: "在真实导演场景新增摄影机；要求最新 expectedSceneHash，保存后回读摄影机 ID。",
    canvas_update_director_camera: "修改真实摄影机名称、三维变换、视线目标与镜头参数；要求最新 expectedSceneHash，保存后回读。",
    canvas_delete_director_camera: "删除真实摄影机并把引用它的镜头切换到剩余摄影机；场景至少保留一台，保存后回读。",
    canvas_add_director_light: "在真实导演场景新增环境光、方向光、点光源或聚光灯；要求最新 expectedSceneHash，保存后回读灯光 ID。",
    canvas_update_director_light: "修改真实灯光类型、位置、颜色、强度、阴影等参数；要求最新 expectedSceneHash，保存后回读。",
    canvas_delete_director_light: "按真实 lightId 删除导演场景灯光；要求最新 expectedSceneHash，保存后回读。",
    canvas_add_director_object: "在真实导演场景新增 primitive 或 actor 对象，并按场景已有对象避让定位；要求最新 expectedSceneHash，保存后回读对象 ID。",
    canvas_update_director_object: "按真实 objectId 修改导演对象名称、颜色、可见性或三维变换；要求最新 expectedSceneHash，保存后回读。",
    canvas_delete_director_object: "按真实 objectId 删除导演对象；要求最新 expectedSceneHash，保存后回读。",
    canvas_upsert_director_keyframe: "在导演场景的对象变换轨或摄影机轨按秒数写入或更新关键帧；要求最新 expectedSceneHash 和明确的 transform，保存后回读关键帧。",
    canvas_delete_director_keyframe: "按真实关键帧 ID 删除导演对象变换轨或摄影机轨关键帧；要求最新 expectedSceneHash，保存后回读。",
    canvas_upsert_director_bone_keyframe: "在演员对象的真实骨骼轨道按秒数写入或更新四元数关键帧；要求最新 expectedSceneHash，保存后回读。",
    canvas_delete_director_bone_keyframe: "按真实骨骼及关键帧 ID 删除演员对象骨骼关键帧；要求最新 expectedSceneHash，保存后回读。",
    canvas_get_capabilities: "返回画布 MCP 工具目录和批量操作能力，注明读写、可逆性及是否会触发生成费用。",
    canvas_list_open_canvases: "列出当前在线画布的安全摘要（画布 ID、标题、clientId、版本、状态哈希和短剧项目 ID），不返回节点内容或媒体信息。多画布时先调用它，再把 canvasId 传给目标工具；同画布多标签还需 clientId。",
    canvas_layout_nodes: "整理画布为留白一致、无重叠的网格。auto 按媒体用途分块排列，grid 使用均衡网格。明确 ids 只整理对应范围；ids=[] 明确整理整张画布；省略 ids 时优先选区，没有选区则整理全图。Frame/文件夹及子节点可能随范围调整；保留锁定节点和原连线。默认传本次相关节点 ID，用户要求整体整理时才传空列表。flow/row/column 按用户布局意图选用。返回分组范围与保留节点。操作无生成费用、可撤销；先读当前画布版本和状态哈希。",
    canvas_undo_agent_ops: "调用衍图页面原生 Agent 操作历史，只撤销当前画布 Agent 最近一次尚未被用户操作打断的 MCP 修改；不执行反向 ops。需要当前 Agent 操作历史中有可撤销项，先读取 canvas_get_context 并传 expectedRevision 和 expectedStateHash。撤销无费用，返回恢复后的完整快照。",
    canvas_redo_agent_ops: "调用衍图页面原生 Agent 操作历史，只重做当前画布最近一次 Agent 撤销；使用 canvas_get_context 的状态前置条件，用户或其他 Agent 修改会使重做失效。不执行反向 ops或生成。",
    canvas_duplicate_node: "调用画布原生复制操作复制指定节点（Frame 会连同子节点复制，并保留内部引用与连线语义）；不通过 add_node 拼装副本。传真实 nodeId 及 canvas_get_context 的 expectedRevision/stateHash。复制无生成费用，返回新节点和连线 ID 并回读验证。",
    canvas_toggle_node_locked: "调用画布原生锁定切换操作切换指定节点的位置/尺寸锁定状态；传真实 nodeId 及 canvas_get_context 的 expectedRevision/stateHash。返回新的 locked 状态并回读验证。",
    canvas_toggle_frame_collapsed: "调用画布原生 Frame 折叠切换，仅接受真实 Frame 节点；传真实 nodeId 及 canvas_get_context 的 expectedRevision/stateHash。返回 collapsed 状态并回读验证。",
    canvas_insert_asset: "把素材库或当前短剧项目中的既有素材按原生页面插入流程加入指定画布；需提供真实 assetId 和目标画布状态前置条件。只引用现有资源，不触发生成；返回新节点及持久化资源引用供回读核验。",
    canvas_replace_node_media: "用素材库或当前短剧项目的既有图片/视频/音频资源替换同类型媒体节点，复用页面原生素材转换/入库流程并保留节点 ID 与位置。需真实 nodeId、assetId 和目标画布状态前置条件；不触发生成。",
    canvas_export_color_grade: "将已连接图片的调色节点按当前预览参数烘焙为真实 PNG 图片资源和画布节点；需读取最新画布状态并提供 nodeId、expectedCanvasId、expectedRevision、expectedStateHash。不调用生成模型。",
    canvas_set_panorama_view: "设置已挂载全景节点的真实 WebGL 视角（经度、纬度、视场角）；传最新画布前置条件。节点需先位于当前视口并完成渲染，不修改节点数据、不调用生成模型。",
    canvas_capture_panorama_view: "捕获当前全景节点真实 WebGL renderer 的 PNG；mode=view（默认）捕获当前视角，mode=quad 导出带四向标签的 2x2 真实渲染图。通过画布上传流程创建持久化图片资源节点；先用 canvas_set_panorama_view 定好视角、必要时用 canvas_set_viewport 将全景节点放入视口。需最新画布前置条件；不调用生成模型。",
    canvas_inspect_node_render: "只读检查当前页面已挂载节点的可见 DOM 诊断信息（边界、可见性、内容类别计数）。不会切换视口。HTML/SVG 沙箱 iframe 仅报告 iframe 加载状态与外框尺寸，不读取跨域内部或声称截图验收。",
    canvas_get_timeline: "读取当前目标画布持久化时间线和 expectedHash。后续写入需要使用同一 expectedHash，并提供当前 canvas_get_context 的画布状态前置字段。",
    canvas_apply_timeline_operation: "对当前目标画布的时间线执行一个受类型约束的片段、字幕、轨道或音量/淡入淡出操作；使用 canvas_get_timeline 返回的 expectedHash 和当前 canvas_get_context 的 expectedCanvasId/revision/stateHash。操作前后校验持久化版本与字幕节点回读，不触发生成；clip.insert 仅接受已解析且有时长证据的片段。",
    canvas_render_timeline: "以当前画布持久化时间线和页面原生 FFmpeg 渲染器制作 MP4，上传 Resource 并创建可回读的视频节点；要求最新画布状态、canvas_get_timeline 的 expectedHash 及稳定 clientOperationId。包含独立音频时按轨道状态混音；可见字幕、文字和图片按各自时段绘制为透明 PNG 并叠加，格式或解码失败会报错。无模型费用。",
    canvas_upload_file: "从运行 MCP 的本机读取指定媒体文件，经一次性 localhost 流传给当前绑定网页，再调用原生上传流程写入 Resource/Asset 并新增或替换节点。仅限绝对路径、支持的媒体/文本扩展名和 100 MiB；内容 MIME/签名校验，字节绝不经 SSE JSON。写操作需要 expectedCanvasId/revision/stateHash；可选 nodeId 用于同类型替换。",
    canvas_crop_image: "复用页面原生图片裁剪流程，基于归一化裁剪框生成并持久化新图片节点与连线；只做本地图像处理，不调用生成服务。",
    canvas_split_image: "复用页面原生宫格切图流程，将现有图片切分为 rows×columns 个素材节点，持久化并连接回源节点；不调用生成服务。",
    canvas_upscale_image: "复用本地插值算法放大图片（nearest/bilinear/high），生成并持久化新节点；不调用图像生成模型。",
    canvas_extract_video_frames: "复用页面原生视频帧提取流程，从指定毫秒位置提取帧并持久化为图片节点；本地媒体处理，不调用生成服务。",
    canvas_extract_video_audio: "复用原生视频片段工具从已有视频指定区间提取音频，并持久化节点；只提取，不生成音频。",
    canvas_trim_video: "复用原生视频片段工具从已有视频提取一个或多个区间成为新视频节点；action 固定为 extract，不生成视频、不触发生成费用。",
    canvas_convert_media: "执行画布转换节点的六种本地转换：灰度、Canny、AI 线稿、深度、姿态、透明抠图。先连接一张图片或一个视频到转换节点；视频可指定取帧秒数。运行并持久化结果，不调用付费生成服务。",
    canvas_batch_table_read: "读取真实批量创作表格和版本。",
    canvas_batch_table_add_row: "调用批量创作表格原生逻辑新增一行，不生成内容。",
    canvas_batch_table_update_row: "按类型约束更新真实表格行字段，不触发生成。",
    canvas_batch_table_remove_row: "删除批量创作表格指定行并回读。",
    canvas_batch_table_add_reference_column: "在批量创作表格中新增参考图列，不触发生成。",
    canvas_batch_table_remove_reference_column: "删除指定参考图列并清除对应连线。",
    canvas_batch_table_reorder_reference_columns: "调用原生逻辑调整参考图列顺序。",
    canvas_batch_table_move_reference_cell: "在表格行/列之间移动参考图关联。",
    canvas_batch_table_sync_rows_from_connections: "按真实表格连线同步行关联。",
    canvas_edit_reference: "调用页面原生引用控制，在明确目标节点上新增、移除、替换或重排资源引用；维护参考连线与提示词同步并回读真实引用。仅接受显式节点 ID，使用当前画布状态前置条件，不触发生成。",
    canvas_preflight_batch_rows: "预检真实批量创作表指定行的生成配置与费用条件；只读，不提交生成。",
    canvas_generate_batch_rows: "调用批量创作表原生逐行生成并沿用网页费用确认；同一 clientOperationId 重试用于恢复同一批次，超时不得换 ID 重提。需要当前画布状态前置条件。",
    canvas_create_local_folder: "调用原生页面逻辑在当前画布创建本机文件夹 Frame。",
    canvas_create_storyboard_group: "调用原生页面逻辑将明确图片节点组成分镜组。",
    canvas_create_reference_group: "调用原生页面逻辑将明确图片/视频节点组成引用组。",
    canvas_move_nodes_to_frame: "调用原生 Frame 拖放逻辑移动明确节点；目标 Frame 为空表示移出 Frame。关联素材文件夹会先确保存储和项目关联。",
    canvas_list_projects: "列出本地画布项目及版本、节点和连接数量。",
    canvas_export_projects: "按画布 ID 与版本前置条件生成并触发浏览器 ZIP 下载；只返回文件元信息，不经 MCP 传输 ZIP 字节。",
    canvas_import_project_archive: "读取运行 MCP 本机的 ZIP，通过一次性 localhost 文件流交给当前画布标签页校验并导入；限制 100 MiB，仅本地项目。",
    canvas_get_context: "读取面向 Agent 的语义化画布上下文。detail=full（默认）包含节点摘要、连接、选区、资源和生成状态；detail=summary 仅返回版本/状态哈希、统计、警告及最多20个选区摘要，明确记录省略数量，适合后续刷新写入前置条件。完整提示词用 canvas_get_node；按需查节点/行/任务，避免每步重传全图。canvasId 用于选定画布，同画布多标签的读取还需 clientId。",
    canvas_find_nodes: "按标题、内容、提示词、类型、状态、资产或工作流检索真实节点，返回可用于后续写操作的节点 id。",
    canvas_find_available_assets: "按条件查找画布可用素材，只返回安全摘要，不返回 URL 或媒体字节。",
    canvas_preflight_storyboard_media: "预检真实 Script 节点指定分镜行的图片/视频生成条件、费用和模型信息；只读，不提交任务。",
    canvas_generate_storyboard_media: "调用页面原生逐行分镜图片/视频生成，沿用产品费用确认，每行按 batch 幂等。先用同 ID 重试恢复不确定批次；超时不得换 ID 重提。需要当前画布状态前置条件。",
    canvas_get_node: "按真实节点 id 精确读取单个节点：语义摘要、完整 content/prompt/composerContent、锁定/折叠标志、分镜结构、资源状态及关联连线。只返回明确开放的 metadata，不返回媒体 URL 或任意配置。找不到时返回 found=false；更新长提示词时读取完整字段，不能用上下文的截断预览覆盖。",
    canvas_get_connection: "按真实连线 id 精确读取连线端点、端点节点摘要和 handle 信息；找不到时明确返回未找到。",
    canvas_get_generation_tasks: "读取当前画布节点已经绑定的生成任务观察状态，包括 taskId、节点、任务状态、进度、阶段和错误；这是画布快照观察，不会主动轮询上游。",
    canvas_get_resources: "读取当前画布引用的媒体资源清单，包括资源/资产引用、类型、尺寸、大小、时长和就绪状态；不会返回媒体 URL。",
    canvas_validate_ops: "在真正写入前校验批量操作中的节点 id、连接关系和参数，避免对不存在节点或错误资源执行操作。",
    canvas_get_selection: "读取当前网页画布选中的节点。",
    canvas_get_storyboard: "读取画布中的 Script 分镜（真实 StoryboardRow）：每行含镜号、时长、剧情、对白、旁白、叙事目的、调度、景别、情绪、灯光、音效、摄影机、运镜、节拍、首帧提示词、视频提示词、必备元素、连续性与资产绑定，以及 rowTrace/segment trace 的节点、任务和资源一致性；traceConsistent=false 时不得把该行报告为可交付完成，也不得猜造任务 ID。多镜头任务先读它，不要把镜头写成普通文本。",
    canvas_update_storyboard: "写入画布真实 Script 分镜。先读取 canvas_get_storyboard 并原样携带 expectedRevision 与 expectedStateHash；replace 已有分镜必须保留每行稳定 rowId，merge 优先按 rowId 匹配，shotNumber 只兼容无 rowId 的旧行。未传字段保留、null/空数组显式清除；requiredAssetRoles 明确本镜硬性依赖的角色/场景/道具等资产，videoOperation 只有在 film_validate_strategy/ProductionPlan 证实当前模型能力后才记录；T2V 无首帧可以合法，但必需资产缺失必须明确显示。durationSeconds 是叙事镜头目标时长，生成请求需按真实模型能力拆成合法片段。",
    canvas_export_snapshot: "导出当前画布快照，用于理解布局。",
    canvas_apply_ops: "批量操作当前网页画布。ops 支持 add_node、update_node、delete_node、delete_connections、connect_nodes、set_viewport、select_nodes、run_generation。",
    canvas_create_workflow: "创建语义化工作流/流水线。character_cards 是角色拆分图片卡片，character_three_view 是角色三视图，storyboard_video 是分镜剧情视频。媒体节点必须有 prompt/content；已有素材使用先读取到的真实 node id 填入 referenceNodeIds。自动分配 id、根据真实节点尺寸布局、建立 edges/referenceRefs/referenceNodeIds 连线并返回可验证结果；不要用批量文本节点代替工作流。",
    canvas_create_node: "通过网页原生 createNode 创建节点，支持内置节点类型和已启用的可创建插件节点；会遵守绘图授权与插件可用性。可选标题/尺寸/metadata 在创建后经受约束的节点更新写入；不会触发生成。",
    canvas_create_storyboard_image_nodes: "按明确 Script 节点和 rowIds 调用页面原生逻辑创建/复用分镜图片节点，维护 rows、prompt 与 storyboard-output/reference 连线；不生成图片、不收费。",
    canvas_create_storyboard_video_nodes: "按明确 Script 节点和 rowIds 调用页面原生逻辑创建/复用待生成视频节点，维护分镜行绑定、提示词和连线；只建结构，不提交生成任务。",
    canvas_generate_storyboard_rows: "调用网页原生 AI 拆镜流程，保留现有报价与用户确认步骤；必须提供可重试复用的稳定 clientOperationId。只接受有报价、确认和幂等托管任务路径；返回最终任务/行结果，不会自动批准费用。",
    canvas_create_text_node: "在当前画布创建单个文本节点。",
    canvas_create_text_nodes: "批量创建文本节点，适合生成标题、段落、脚本、说明等内容块。",
    canvas_create_image_prompt_flow: "创建提示词文本节点和图片目标节点并自动连线，可选择立即触发生图。",
    canvas_create_generation_flow: "创建通用生成流程：提示词文本节点、对应类型的生成目标节点和参考节点连线，可用于文案、生图、视频或音频；视频可显式传 videoOperation、videoRatio、videoResolution、videoSeconds 及首尾帧节点 ID。",
    canvas_generate_text: "创建通用文本生成流程并立即触发生成。相同输入默认复用稳定 clientOperationId；超时或状态不确定时先查任务并用同一 ID 重试。确需再次生成相同内容时传新的 clientOperationId。",
    canvas_generate_image: "创建通用图片生成流程并立即触发生图。相同输入默认复用稳定 clientOperationId；超时或状态不确定时先查任务并用同一 ID 重试。确需再次生成相同内容时传新的 clientOperationId。",
    canvas_generate_video: "创建通用视频生成流程并立即触发生成。视频参数用 videoOperation、videoRatio、videoResolution、videoSeconds；图生视频可传 videoStartFrameNodeId，首尾帧模式可再传 videoEndFrameNodeId，工具会建立对应连接并标记帧角色。相同输入默认复用稳定 clientOperationId；超时或状态不确定时先查任务并用同一 ID 重试。确需再次生成相同内容时传新的 clientOperationId。",
    canvas_generate_audio: "创建通用音频生成流程并立即触发生成。相同输入默认复用稳定 clientOperationId；超时或状态不确定时先查任务并用同一 ID 重试。确需再次生成相同内容时传新的 clientOperationId。",
    canvas_update_node: "更新节点基础字段或 metadata。",
    canvas_update_node_text: "更新文本节点内容和标题。",
    canvas_move_nodes: "移动一个或多个节点，支持绝对坐标或 dx/dy 偏移。",
    canvas_resize_node: "调整节点尺寸。",
    canvas_delete_nodes: "删除指定节点及相关连线。",
    canvas_connect_nodes: "批量连接节点。",
    canvas_select_nodes: "设置当前选中节点。",
    canvas_set_viewport: "调整画布视口。",
    canvas_run_generation: "触发指定节点生成；超时或状态不确定时查询任务并复用同一 clientOperationId，不能换新 ID 重发。对终态失败任务明确重试时传 retry=true，以复用产品级重试幂等身份。",
    canvas_merge_videos: "按给定顺序合并已有视频节点为最终成片：调用页面同款 FFmpeg 合并链路、入库并在画布生成“合并成片”节点；只传已经生成完成的视频节点 id。",
    project_get_context: "读取当前短剧项目的章节、画布、资产、镜头、候选和工作流事实。",
    project_list_units: "按类型或状态筛选当前短剧项目的章节/项目单元。",
    project_list_voices: "读取当前用户可用的 VoiceProfile 档案；只读，不生成试听，也不创建 voiceId。",
    project_bind_character_voice: "将真实 VoiceProfile、已上传参考音频或已存在的上游 voiceId 绑定到项目角色并创建不可变 VoiceVersion。后端会校验模型能力；voiceReference/voiceDesign 未配置时会拒绝，不要虚构 voiceId。",
    project_create_from_script: "从剧本创建短剧项目并保存第一章；这一步不会制作成片。必须提供稳定 clientOperationId 以便超时重试续用同一项目。默认关联当前画布；无画布时创建关联画布，createNewCanvas=true 时始终新建。成功后再用返回的项目/画布 ID 调用 film_list_operations 与 film_list_models 规划后续制作。",
    project_extract_asset_candidates: "将分镜识别出的场景、道具、素材或其他需求登记为待确认资产候选；角色只在剧情章节提取，不通过此工具重复创建。",
    project_confirm_asset_candidate: "确认一个资产候选，创建正式资产或关联已有个人资产。",
    project_create_or_update_shots: "创建或更新项目镜头业务数据，不把镜头状态写进画布 metadata。",
    project_link_shot_asset: "将具体资产版本按首帧、尾帧或参考等用途关联到镜头。",
    project_start_workflow_step: "启动项目或章节制作流程中的一个步骤。",
    project_link_asset: "将个人资产引用到当前短剧项目，不复制媒体文件。",
    project_upsert_asset_version: "为项目资产创建新的设定和提示词版本，保留历史版本。",
    project_register_task_output: "将成功生成任务挂到流程步骤，并登记到具体资产版本和资源表示。",
    film_list_operations: "列出衍图已定义的影视提示词操作（短剧大纲、章节资产提取、角色提取、角色三视图、分镜规划、分镜修复、分镜首帧、分镜视频）及其变量、输出类型与默认链路。开始影视任务前先调用一次，不要自己编造操作名。",
    film_list_models: "读取当前可用模型的操作、参考图/音频数量、时长、画幅、分辨率、原声音频证据与 productionReadiness。用户限定视频系列（如 MiniMax H3）时传 videoModelFamily=minimax_h3；要求成品有声时传 audioOutputRequired=true，它会优先推荐有声音开关或实测带音轨的型号，但生成后仍须逐段验收。型号后缀不能代替能力证明。缺少能力版本、原生音轨证据或费用时如实报告，不得猜测。",
    film_sync_local_models: "将当前便携版网页里已配置的本地模型渠道登记到本机后端模型目录，供持久制作步骤使用；只在 film_list_models 报告 server_model_catalog_empty 且用户要制作影片时调用。它不会向上游发生成请求，也不会猜价格或音频能力。调用后重新 film_list_models 核对能力版本及余下阻断原因。",
    film_run_operation: "调用一个已有的影视文本规划/提示词操作；只允许文本模式，短提交并立即返回持久 taskId。先用 film_list_models 确认文本模型有后端能力版本；缺失时调用 film_sync_local_models。必须提供 clientOperationId；提交不确定或重试时复用原 ID，再用 film_wait_task 查询，不在网页桥内等待模型执行完成。图片、视频、音频生成必须走持久化制作步骤 film_submit_step。",
    film_validate_strategy: "用当前模型能力合同只读验证候选策略。用户限定视频系列时传 videoModelFamily；要求成品有声时传 audioOutputRequired=true，它只影响推荐顺序，不等于上游生成声音开关。逐镜检查参考图/参考音频数量、时长、画幅及音频，返回不可行原因和未知项，不发起付费生成。",
    film_create_run: "创建持久化整片制作运行。新建整片采用 productionSpec.workflowVersion=2，先登记剧本拆解、视觉设计、粗分镜、参考资产、声音方案及最终分镜/Animatic产物；阶段证据经检查通过后，代表样片解锁后续批量视频，不能直接从粗分镜跳到生成。普通单节点测试使用 canvas 工具。用户指定 MiniMax H3 等视频系列时传 videoModelFamily，按本渠道真实能力选择型号。默认 NATIVE_AUDIO 保留实测原声；用户明确要求重配才选 REBUILD_AUDIO。最终以镜头质检、连续性、后期和成片验收交付。",
    film_get_run: "按 runId 和事件序号读取权威制作状态、步骤、attempt 与增量事件，用于上下文压缩或新会话接续。",
    film_update_plan: "按 expectedRevision 更新声明式制作计划；变更会使受影响下游步骤失效、保留旧 attempt/产物并返回预计重做费用，计划必须重新授权。仍有未结清任务的步骤不能改写。",
    film_pause_run: "暂停制作运行，停止派发新步骤；已提交的上游任务按真实取消/保存状态处理。",
    film_resume_run: "恢复本用户已暂停或等待输入的制作运行，保留原授权和版本边界。",
    film_cancel_run: "取消制作运行并停止新步骤派发；不会伪造上游取消或退款成功。",
    film_submit_step: "为已授权制作步骤提交一次不可变 attempt；核对持久计划中的模型、能力版本和运行中固定的视频系列限制。未指定视频型号时只在允许的系列及兼容能力内选型；显式 task.model 则锁定。费用已知时使用真实核验的费用预估；仅当 ProductionRun 持久授权明确为 unbounded 时，才允许未知费用以 0 表示 unknown（0 不代表免费、零成本或已核验价格）；有界预算必须提供真实核验的正数预估。服务端仍负责授权、能力及幂等校验；同一幂等键重试只回读既有任务。",
    film_probe_media: "用后端 ffprobe 读取真实资源流信息；fullDecode=true 时执行完整解码，并对视频首、中、尾帧分别取样解码后返回证据；没有实际探测结果时不宣称媒体合格。",
    film_record_model_outputs: "从 1 至 4 个已成功的视频任务核对真实模型、能力版本和资源，完整解码并探测音轨，把有声/无声样本作为观察证据写回该渠道模型目录。不会开启上游不支持的声音开关，也不会把单个无声样本当成模型永远无声。生成完成后调用此工具，让后续 Agent 能按实测证据选型。",
    film_check_shot: "检查单个镜头资源的流、时长、完整解码和必需音轨；只返回程序可验证事实，语义检查缺失时标记 unavailable。",
    film_self_check: "只读汇总指定画布图片/视频的真实资源解码、当前 ProductionRun 逐项验收、漏检/过期证据和声音听审状态，返回待检查队列与实际可用工具。最多120个资源，每次默认20；省略 nodeIds 检查全部媒体。不会生成、采用或写入质量通过，ASR/任务成功/审美无问题不代替内容验收。",
    canvas_read_quality_reports: "只读读取现有 AI 审美批改/肖像分析节点的真实报告、输入和 taskId；源图改变则报告失效。报告作为自检和修图定位依据，审美报告不能代替影片连续性、手部和声音检查；不启动收费分析。",
    film_record_step_result: "将实际阶段产物、质检或连续性证据写回 ProductionStep，使用最新 run revision。正式 stage:* 检查需要与锁定计划一致的产物、版本、输入指纹和实际检查，不能空写通过；依赖未完成不会放行。reuse_media 只提交 manifest 绑定的 resourceId，由服务端核对归属、真实来源任务、解码、画幅和长度。连续性技能要提交真实已读版本/哈希、rowId、输入指纹及实际应用结果；未验证的语义质量记 uncertain，不能冒充通过。",
    film_render_timeline: "提交 ProductionRun 主时间线并立即返回 taskId；每个视频片段须回绑 manifest 的 storyboardRowId/segmentId 和最新成功生成任务的真实资源，音轨与字幕也须保留分镜/轨道追踪；服务端会拒绝错误素材、时长、画幅或帧率。重试用相同 idempotencyKey 读取原 task，只有已结清失败的 render attempt 才能用 retryOf 创建新尝试。渲染生命周期由任务查询与事件恢复，不绑定 MCP 长连接。",
    film_verify_delivery: "对最终资源执行完整解码与交付合同核验，分别返回 passed/failed/uncertain，未通过必需条件时不得标记完成。",
    film_get_tasks: "每次最多按任务 ID 查询 20 个真实任务；更多任务请分批。返回服务端 nextPollAt、任务 errorCode，以及查询失败时的结构化 queryError（HTTP/业务码、reason、retryable、retryAfterMs）；waitMs 总时限受 30 秒桥约束。查询失败或等待超时后只按 nextPollAt/retryAfterMs 重查原 taskId，不取消或重发上游任务。",
    film_wait_task: "在 30 秒桥时限内等待或查询一个已提交的生成任务直到终态，返回状态、进度、errorCode、结构化查询错误和产物；超时表示任务仍在进行，可以稍后按 nextPollAt/retryAfterMs 查询同一 taskId，不要重复提交同一任务。",
};

for (const name of toolNames) {
    if (name.startsWith("canvas_") && !canvasReadOnlyTools.has(name)) {
        toolDescriptions[name] += " 本画布写操作必须显式提供 expectedCanvasId、expectedRevision、expectedStateHash；从 canvas_get_context.canvas.projectId 与状态字段取值，画布不匹配或状态已变化时会拒绝执行。";
    }
}
